on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            bin: regexify-cli
            name: Windows-x86_64
            archive: zip
          - target: x86_64-unknown-linux-musl
            bin: regexify-cli
            name: Linux-x86_64
            archive: tar.gz
          - target: x86_64-apple-darwin
            bin: regexify-cli
            name: MacOS
            archive: zip
    steps:
      - uses: actions/checkout@v2

      - name: Get version from Cargo.toml
        run: |
          version=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="${{ matrix.bin }}") | .version')
          echo "VERSION=${version}" >> $GITHUB_ENV
        shell: bash

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MACOSX_DEPLOYMENT_TARGET: 10.12
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: regexify-cli_${{ env.VERSION }}_${{ matrix.name }}