on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            bin: regexify-cli
            name: Windows-x86_64
            archive: zip
          - target: x86_64-unknown-linux-musl
            bin: regexify-cli
            name: Linux-x86_64
            archive: tar.gz
#          - target: x86_64-apple-darwin
#            bin: regexify-cli
#            name: MacOS
#            archive: zip
    steps:
      - uses: actions/checkout@v2

      - name: Get version from Cargo.toml
        run: |
          version=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="${{ matrix.bin }}") | .version')
          echo "VERSION=${version}" >> $GITHUB_ENV
        shell: bash

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MACOSX_DEPLOYMENT_TARGET: 10.10
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: regexify-cli_${{ env.VERSION }}_${{ matrix.name }}
  build-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig
        run: |
          wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
          tar -xf zig-linux-x86_64-0.11.0.tar.xz
          echo "$(pwd)/zig-linux-x86_64-0.11.0" >> $GITHUB_PATH

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build for macOS using Zig
        run: cargo zigbuild --target x86_64-apple-darwin --release

      - name: Archive Binary
        run: |
          mkdir -p dist
          cp target/x86_64-apple-darwin/release/regexify-cli dist/
          tar -czvf dist/regexify-cli_macos.tar.gz -C dist regexify-cli

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/dist/regexify-cli_macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}